name: Build Multiplatform project
on:
  push:
    branches:
      - main
      - feature/ci_support
  pull_request:

jobs:
  build-multiplatform-project:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-12, windows-2022]
        gradle: [8.3]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build Multiplatform project
        shell: bash
        run: ./gradlew assemble